version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
  
  odoo:
    image: odoo:17
    depends_on:
      - db
    ports:
      - '8069:8069'
